[helpers]

[default]
depends = []

[default.files]

[default.variables]

[i3.files]
"i3" = "~/.config/i3"

[feh.files]
"fehbg" = "~/.fehbg"

[betterlockscreen.files]
"betterlockscreen" = "~/.config/betterlockscreen"

[dunst.files]
"dunst" = "~/.config/dunst"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[btop.files]
"btop" = "~/.config/btop"

[fish.files]
"fish" = "~/.config/fish"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[xprofile.files]
"xprofile" = "~/.xprofile"

[polybar.files]
"polybar" = "~/.config/polybar"

[rofi.files]
"rofi" = "~/.config/rofi"

[qt6ct.files]
"qt6ct" = "~/.config/qt6ct"

[qt5ct.files]
"qt5ct" = "~/.config/qt5ct"

[Xresources.files]
"Xresources" = "~/.Xresources"

[mpd.files]
"mpd" = "~/.config/mpd"

[ncmpcpp.files]
"ncmpcpp" = "~/.config/ncmpcpp"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[startpage.files]
"startpage" = "~/.config/startpage"

[ranger.files]
"ranger" = "~/.config/ranger"

[yazi.files]
"yazi" = "~/.config/yazi"

[conky.files]
"conky" = "~/.config/conky"
