[helpers]

[default]
depends = []

[default.files]

[default.variables]

[i3.files]
"i3" = "~/.config/i3"

[feh.files]
"fehbg" = "~/.fehbg"

[betterlockscreen.files]
"betterlockscreen" = "~/.config/betterlockscreen"

[dunst.files]
"dunst" = "~/.config/dunst"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[btop.files]
"btop" = "~/.config/btop"

[fish.files]
"fish" = "~/.config/fish"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[xprofile.files]
"xprofile" = "~/.xprofile"
